config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'restaurants/index'
  get 'restaurants/show'
  get 'restaurants/new'
  get 'restaurants/create'
  get 'restaurants/edit'
  get 'restaurants/update'
  get 'restaurants/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  CATEGORY = %w[chinese italian japanese french belgian]
  validates :name, presence: true
  validates :category, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end
    # @restaurant.save
    # redirect_to restaurant_path(@restaurant)

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORY %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<ul class="list-group mb-4">
  <% @restaurants.each do |restaurant| %>
    <li class="list-group-item d-flex justify-content-between align-items-center"><%= link_to restaurant["name"], restaurant_path(restaurant["id"]), class: "text-decoration-none" %>
    <%= link_to restaurant_path(restaurant), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger btn-sm" do%>
      <i class="fa-regular fa-trash-can"></i>
      <% end %>
    </li>
  <% end %>
</ul>
<%= link_to "Create a new restaurant", new_restaurant_path, class: "btn btn-primary"%>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<figure class="text-center my-5">
  <blockquote class="blockquote">
    <p><%= @restaurant.name %></p>
  </blockquote>
  <figcaption class="blockquote-footer">
    <p><%= @restaurant.address %></p>
    <p><%= @restaurant.phone_number %></p>
    <p><%= @restaurant.category %></p>
    </figcaption>
   <blockquote class="blockquote">
    <p>Reviews</p>
    <ul>
      <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item"><%= review.content %></li>
    <li class="list-group-item"><%= review.rating.to_s %></li>
  <% end %>
</ul>
</blockquote>
</figure>
<div class = "d-grid gap-2 col-6 mx-auto">
<%= link_to "add a review", new_restaurant_review_path(@restaurant), class: "btn btn-primary text-center" %>
<%= link_to "Edit restaurant", edit_restaurant_path, class: "btn btn-primary text-center"%>
<%= link_to "Back to list", restaurants_path, class: "btn btn-primary " %>
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
<%= link_to "Back to list", restaurants_path, class: "btn btn-primary " %>